/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = [''];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovdXNlcnMvaGFzc29uYS9kZXNrdG9wL3Rlc3QvYmxvZy1hcHAvc3JjL2FwcC9wb3N0cy9uZXctcG9zdC9uZXctcG9zdC5jb21wb25lbnQuY3NzLnNoaW0ubmdzdHlsZS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L3VzZXJzL2hhc3NvbmEvZGVza3RvcC90ZXN0L2Jsb2ctYXBwL3NyYy9hcHAvcG9zdHMvbmV3LXBvc3QvbmV3LXBvc3QuY29tcG9uZW50LmNzcyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
