/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './app.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from './header/header.component.ngfactory';
import * as i3 from './header/header.component';
import * as i4 from '@angular/router';
import * as i5 from './app.component';
const styles_AppComponent:any[] = [i0.styles];
export const RenderType_AppComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,styles:styles_AppComponent,
    data:{}});
export function View_AppComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵted(-1,(null as any),['\n'])),(_l()(),i1.ɵeld(1,0,
      (null as any),(null as any),1,'app-header',([] as any[]),(null as any),(null as any),
      (null as any),i2.View_HeaderComponent_0,i2.RenderType_HeaderComponent)),i1.ɵdid(2,
      114688,(null as any),0,i3.HeaderComponent,([] as any[]),(null as any),(null as any)),
      (_l()(),i1.ɵted(-1,(null as any),['\n'])),(_l()(),i1.ɵeld(4,0,(null as any),
          (null as any),4,'div',[['class','container']],(null as any),(null as any),
          (null as any),(null as any),(null as any))),(_l()(),i1.ɵted(-1,(null as any),
          ['\n    '])),(_l()(),i1.ɵeld(6,16777216,(null as any),(null as any),1,'router-outlet',
          ([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
      i1.ɵdid(7,212992,(null as any),0,i4.RouterOutlet,[i4.ChildrenOutletContexts,
          i1.ViewContainerRef,i1.ComponentFactoryResolver,[8,(null as any)],i1.ChangeDetectorRef],
          (null as any),(null as any)),(_l()(),i1.ɵted(-1,(null as any),['\n'])),(_l()(),
          i1.ɵted(-1,(null as any),['\n']))],(_ck,_v) => {
    _ck(_v,2,0);
    _ck(_v,7,0);
  },(null as any));
}
export function View_AppComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'app-root',([] as any[]),
      (null as any),(null as any),(null as any),View_AppComponent_0,RenderType_AppComponent)),
      i1.ɵdid(1,49152,(null as any),0,i5.AppComponent,([] as any[]),(null as any),
          (null as any))],(null as any),(null as any));
}
export const AppComponentNgFactory:i1.ComponentFactory<i5.AppComponent> = i1.ɵccf('app-root',
    i5.AppComponent,View_AppComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovdXNlcnMvaGFzc29uYS9kZXNrdG9wL3Rlc3QvYmxvZy1hcHAvc3JjL2FwcC9hcHAuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L3VzZXJzL2hhc3NvbmEvZGVza3RvcC90ZXN0L2Jsb2ctYXBwL3NyYy9hcHAvYXBwLmNvbXBvbmVudC50cyIsIm5nOi8vL0M6L3VzZXJzL2hhc3NvbmEvZGVza3RvcC90ZXN0L2Jsb2ctYXBwL3NyYy9hcHAvYXBwLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovdXNlcnMvaGFzc29uYS9kZXNrdG9wL3Rlc3QvYmxvZy1hcHAvc3JjL2FwcC9hcHAuY29tcG9uZW50LnRzLkFwcENvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIlxuPGFwcC1oZWFkZXI+PC9hcHAtaGVhZGVyPlxuPGRpdiBjbGFzcz1cImNvbnRhaW5lclwiPlxuICAgIDxyb3V0ZXItb3V0bGV0Pjwvcm91dGVyLW91dGxldD5cbjwvZGl2PlxuIiwiPGFwcC1yb290PjwvYXBwLXJvb3Q+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7O29CQ0FBLDBDQUNBO01BQUE7TUFBQSwrRUFBQTtNQUFBO01BQXlCLDBDQUN6QjtVQUFBO1VBQUEsNENBQXVCO1VBQUEsYUFDbkI7VUFBQTthQUFBOzBEQUFBO1VBQUEsNkJBQStCLDBDQUM3QjtpQkFBQTtJQUhOO0lBRUk7Ozs7b0JDSEo7TUFBQTthQUFBO1VBQUE7OzsifQ==
